### ISSUE TITLE
Roadmap SOS.js - OL3

### ISSUE THREAD

**Issue by glacunza** [52North/sos-js#34]
Which is your roadmap regarding the development of sos.js in OpenLayers3 with the implementation of version 2.0.0 of the standard of SOS? We have checked that sos.js is based on parsers of OL2.

**Comment by jruizaranguren** [comment]
I wonder also whether it would make sense to enhance the sos.js client in order to reduce dependencies (get rid of OL completely). But I might be underestimating the required effort.

**Comment by nuest** [comment]
That surely is a very interesting idea, I'm sure @paul-breen would welcome it if you could contribute evaluating that direction. Are you aware of the project jsonix https://github.com/highsource/jsonix ?

**Comment by jruizaranguren** [comment]
@nuest, 52North sos implementation has already a (non-official non-standard) JSON binding that could also be leveraged. It already has nicely documented [json-schemas](https://github.com/52North/SOS/tree/e0eeee8cb5df425908b6d13df02fcec30d24d3d7/coding/json-common/src/main/resources/schema). Perhaps the idea of bindings could also be used in the client.

**Comment by nuest** [comment]
If you are happy with non-standard JSON that can change at any time, that could be an approach...

**Comment by paul-breen** [comment]
Yes, ideally, we would like to get rid of the OL dependencies completely.  As @nuest has mentioned, the jsonix project would be a very good, lightweight, focussed replacement.  I'm less inclinded toward the 52North JSON binding, as it is non-standard, and I believe one of the strengths of sos-js is that it is standards-compliant.  That said, we could support multiple, user-selectable bindings, as @jruizaranguren mentions.

This is something that I'm very interested in, but am struggling at the moment to find the time to implement.  Again, as @nuest mentions, any contributions to replacing the OL parsing functions would be most welcome.

The SOS requests and response parsing are limited to a few functions, all contained in the core SOS.js module, so this shouldn't be too difficult to replace.  However, we also made use of some features of OL, such as its support for "Classes".  We could replicate this functionality in the core module, and then use it throughout.  I think this would be prefereable to a complete redesign, but I'm open to suggestions, and especially open to contributions!

**Comment by jruizaranguren** [comment]
It seems that part of this has already been implemented. There is a project with [jsonix bindings for ogc-schemas](https://github.com/highsource/ogc-schemas)

**Comment by doublebyte1** [comment]
Hi, I am wondering what is the current state of this issue. OL3 still does not have support for SOS, and OL2 only supports version 1.0.0. A OL3 client for SOS is very much missed...

**Comment by paul-breen** [comment]
Our friends at GeoSmartCity have developed a compatible redesign of SOS.js ([gsc-sos.js](https://github.com/GeoSmartCity-CIP/gsc-sos.js)), which amongst other things, removes the hard dependency on OL2 completely.  So you should be able to use gsc-sos.js alongside OL3, or indeed any other mapping library (leaflet).

**Comment by paul-breen** [comment]
There's been no contrary response to my answer, so I'm closing this issue.
